# Generated by Django 5.0.1 on 2024-02-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
