# Generated by Django 5.0.1 on 2024-02-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_student_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_username", models.IntegerField()),
                ("input_year", models.IntegerField()),
                ("input_month", models.IntegerField()),
                ("input_day", models.IntegerField()),
                ("input_text", models.CharField(max_length=100)),
                ("input_time", models.TimeField()),
            ],
        ),
    ]
