# Generated by Django 5.0.1 on 2024-02-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="input_time",
            field=models.CharField(max_length=100),
        ),
    ]
